import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useUser } from "@auth0/nextjs-auth0";

const Home: NextPage = () => {
  const { user, error, isLoading } = useUser();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/authRequired">
          <a>Click to see the /authRequired page</a>
        </Link>
        <div className={styles.user}>
          User {user?.name ? user.name : "not logged in"}
        </div>
        <div className={styles.buttons}>
          <a href="/api/auth/login">
            <button className={styles.button}>Login</button>
          </a>
          <a href="/api/auth/logout">
            <button className={styles.button}>Logout</button>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
